# Self-contained profile for student data exercise
clickhouse_ftw:
  target: remote
  outputs:
    local:
      type: clickhouse
      host: clickhouse          # LOCAL all-in-one: keep "clickhouse"
      port: 8123
      user: ftw_user            # same creds you already use
      password: ftw_pass
      schema: mart              # ClickHouse "database"
      threads: 4
      secure: false

    remote:
      type: clickhouse
      host: 54.87.106.52       # Remote server IP
      port: 8123
      user: ftw_user
      password: ftw_pass
      schema: mart
      threads: 4
      secure: false