# .dlt/secrets.toml
# ClickHouse credentials for remote database connection

[destination.clickhouse.credentials]
host = "54.87.106.52"
http_port = 8123
username = "ftw_user"
password = "ftw_pass"
database = "raw"
secure = 0
connect_timeout = 60
send_receive_timeout = 300

# ─────────────────────────────────────────────────────────────────────────────
# Coingecko Pro credentials for your `bitcoin_prices` resource
# ─────────────────────────────────────────────────────────────────────────────
[coingecko]
# Replace this with the API key you obtained from Coingecko's Pro plan
api_key = "secret"